export interface Meme {
  id: string;
  imageUrl: string;
  sourceUrl: string;
  reactions: { [key: string]: number };
  comments: string[];
  userReaction: string | null;
  isApproved: boolean;
  isAutoGenerated: boolean;
}

export interface GeneratedMemeData {
  imageUrl: string;
}